(function(){
    'use strict';
    const STORAGE_KEY='enterpriseAiInterviewLab.v1';
    const form=document.getElementById('interviewForm');
    const saveStatus=document.getElementById('saveStatus');
    const clientDimensions=[['pain','痛点强度'],['budgetScore','预算能力'],['authority','决策权'],['timing','启动时点'],['delivery','交付可行性']];
    const scenarioDimensions=[['value','业务价值'],['frequencyScore','发生频率'],['standard','标准化程度'],['data','数据可得性'],['willingness','负责人意愿']];
    const clientScores=document.getElementById('clientScores');
    const scenarioScores=document.getElementById('scenarioScores');
    let timerSeconds=1800,timerId=null,saveTimer=null,activeStage=0;
    const stageIds=['stage-background','stage-trigger','stage-process','stage-risk','stage-next'];
    const stageNames=['企业背景','目标与触发','流程还原','成本与风险','意愿与下一步'];

    function scoreControl(key,label,max){return `<label class="score-item"><span>${label}</span><select data-score="${key}">${Array.from({length:max+1},(_,i)=>`<option value="${i}">${i} · ${i===0?'未判断':i===max?'明确':'一般'}</option>`).join('')}</select></label>`}
    clientScores.innerHTML=clientDimensions.map(item=>scoreControl(item[0],item[1],3)).join('');
    scenarioScores.innerHTML=scenarioDimensions.map(item=>scoreControl(item[0],item[1],5)).join('');

    function values(){const data={};new FormData(form).forEach((v,k)=>data[k]=v);data.scores={};document.querySelectorAll('[data-score]').forEach(el=>data.scores[el.dataset.score]=Number(el.value));data.riskScore=Number(document.getElementById('riskScore').value);data.updatedAt=new Date().toISOString();return data}
    function restore(data){if(!data)return;Object.entries(data).forEach(([key,value])=>{if(key==='scores'||key==='riskScore'||key==='updatedAt')return;const fields=form.elements.namedItem(key);if(!fields)return;if(fields instanceof RadioNodeList){Array.from(fields).forEach(el=>el.checked=el.value===value)}else fields.value=value});Object.entries(data.scores||{}).forEach(([key,value])=>{const el=document.querySelector(`[data-score="${key}"]`);if(el)el.value=value});if(data.riskScore)document.getElementById('riskScore').value=data.riskScore}
    function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(values()));saveStatus.textContent=`已本地保存 ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`}
    function scheduleSave(){saveStatus.textContent='正在保存…';clearTimeout(saveTimer);saveTimer=setTimeout(save,350)}
    function esc(value){return String(value||'').trim()||'待确认'}
    function sum(keys,data){return keys.reduce((total,item)=>total+Number(data.scores[item[0]]||0),0)}
    function updateScores(){const data=values(),client=sum(clientDimensions,data),scenario=sum(scenarioDimensions,data),risk=data.riskScore;document.getElementById('clientScore').textContent=client;let grade='C 级',clientAdvice='信息不足，暂不投入定制时间。';if(client>=12){grade='A 级';clientAdvice='48 小时内预约深度诊断。'}else if(client>=8){grade='B 级';clientAdvice='进入培育，每周跟进并补足证据。'}document.getElementById('clientGrade').textContent=grade;document.getElementById('clientAdvice').textContent=clientAdvice;document.getElementById('scenarioScore').textContent=scenario;let scenarioGrade='暂不建议',scenarioAdvice='当前不建议优先投入 AI 改造。';const net=scenario-risk;if(net>=18){scenarioGrade='优先诊断';scenarioAdvice='高价值、较易实施；进入诊断验证基线。'}else if(net>=11){scenarioGrade='需要补证据';scenarioAdvice='先补足流程、数据和负责人证据。'}document.getElementById('scenarioGrade').textContent=scenarioGrade;document.getElementById('scenarioAdvice').textContent=scenarioAdvice;updateEvidence(data);updateProgress(data)}
    function missing(data){const checks=[['company','企业名称'],['triggerQuote','购买触发'],['target90','90 天目标'],['processName','具体流程'],['duration','单次耗时'],['frequency','发生频率'],['dataSource','数据来源'],['pilotOwner','试点负责人'],['nextAction','下一动作'],['nextMeeting','下一次会议日期']];return checks.filter(item=>!String(data[item[0]]||'').trim()).map(item=>item[1])}
    function updateEvidence(data){const items=missing(data),ul=document.getElementById('missingEvidence');ul.innerHTML=(items.length?items:['关键证据已记录']).map(item=>`<li>${item}</li>`).join('')}
    function updateProgress(data){const keys=['company','contact','industry','triggerQuote','target90','processName','processQuote','duration','frequency','bottleneck','dataSource','constraints','pilotOwner','nextStep','nextAction','nextMeeting'];const done=keys.filter(k=>String(data[k]||'').trim()).length;const pct=Math.round(done/keys.length*100);document.getElementById('progressText').textContent=`${pct}%`;document.getElementById('progressBar').style.width=`${pct}%`}
    function line(label,value){return `- **${label}：** ${esc(value)}`}
    function summary(data){const client=sum(clientDimensions,data),scenario=sum(scenarioDimensions,data),risk=data.riskScore,grade=client>=12?'A 级':client>=8?'B 级':'C 级',scenarioGrade=scenario-risk>=18?'优先诊断':scenario-risk>=11?'需要补证据':'暂不建议';return `# ${esc(data.company)}｜企业 AI 初谈纪要\n\n> 访谈日期：${esc(data.interviewDate)}  \n> 联系人：${esc(data.contact)}（${esc(data.role)}）  \n> 本纪要用于需求判断，不构成完整解决方案、实施承诺或正式报价。\n\n## 1. 企业背景\n\n${line('行业 / 规模',`${esc(data.industry)} / ${esc(data.companySize)} 人`)}\n${line('涉及部门',data.department)}\n${line('决策角色',data.decisionRole)}\n${line('内部推动者',data.champion)}\n\n## 2. 目标与触发\n\n${line('客户原话',data.triggerQuote)}\n${line('90 天目标',data.target90)}\n${line('不处理的影响',data.inactionCost)}\n${line('顾问判断',data.triggerJudgement)}\n\n## 3. 真实业务流程\n\n${line('流程',data.processName)}\n${line('执行人',data.processOwner)}\n${line('客户描述',data.processQuote)}\n${line('输入 → 输出',`${esc(data.processInput)} → ${esc(data.processOutput)}`)}\n${line('耗时 / 频率',`${esc(data.duration)} / ${esc(data.frequency)}`)}\n${line('当前工具',data.currentTools)}\n${line('返工、等待或错误',data.bottleneck)}\n${line('顾问判断',data.processJudgement)}\n\n## 4. 成本、数据与风险\n\n${line('涉及人数',data.peopleCount)}\n${line('人工或等待成本',data.manualCost)}\n${line('返工或错误',data.errorCost)}\n${line('数据来源 / 敏感度',`${esc(data.dataSource)} / ${esc(data.dataSensitivity)}`)}\n${line('脱敏样本',data.sampleAvailable)}\n${line('必须人工审核',data.humanReview)}\n${line('限制',data.constraints)}\n${line('顾问判断',data.riskJudgement)}\n\n## 5. 机会判断\n\n${line('客户机会',`${client}/15，${grade}`)}\n${line('业务场景',`${scenario}/25，实施风险 ${risk}/5，${scenarioGrade}`)}\n${line('待补证据',missing(data).join('、')||'暂无') }\n\n## 6. 下一步\n\n${line('建议路径',data.nextStep)}\n${line('下一动作',data.nextAction)}\n${line('负责人',data.actionOwner)}\n${line('会议日期',data.nextMeeting)}\n${line('客户原话',data.nextQuote)}\n${line('最终判断',data.finalJudgement)}\n${line('案例授权',data.casePermission)}\n`}
    function openSummary(){const data=values(),miss=missing(data),text=summary(data);document.getElementById('summaryTitle').textContent=data.company||'未命名企业';document.getElementById('summaryOutput').value=text;const warnings=document.getElementById('summaryWarnings');warnings.hidden=!miss.length;warnings.textContent=miss.length?`还有 ${miss.length} 项关键证据未记录：${miss.join('、')}。你仍可导出，但不要把“待确认”当作客户事实。`:'';document.getElementById('summaryDialog').showModal()}
    function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
    function safeName(data){return `${(data.company||'未命名企业').replace(/[\\/:*?"<>|]/g,'-')}-${data.interviewDate||new Date().toISOString().slice(0,10)}`}
    function updateTimer(){const abs=Math.abs(timerSeconds),min=Math.floor(abs/60),sec=abs%60,el=document.getElementById('timer');el.textContent=`${timerSeconds<0?'+':''}${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;el.classList.toggle('over',timerSeconds<0)}
    function toggleTimer(){const btn=document.getElementById('timerButton');if(timerId){clearInterval(timerId);timerId=null;btn.textContent='继续计时'}else{timerId=setInterval(()=>{timerSeconds--;updateTimer()},1000);btn.textContent='暂停计时'}}
    form.addEventListener('input',()=>{scheduleSave();updateScores()});form.addEventListener('change',()=>{scheduleSave();updateScores()});document.querySelectorAll('[data-score],#riskScore').forEach(el=>el.addEventListener('change',()=>{scheduleSave();updateScores()}));
    function showStage(index){activeStage=Math.max(0,Math.min(stageIds.length-1,index));document.querySelectorAll('.form-section').forEach((section,i)=>section.classList.toggle('active',i===activeStage));document.querySelectorAll('#stageNav button').forEach((button,i)=>button.classList.toggle('active',i===activeStage));document.getElementById('previousStageButton').disabled=activeStage===0;const next=document.getElementById('nextStageButton');next.textContent=activeStage===stageIds.length-1?'生成访谈纪要':`下一步：${stageNames[activeStage+1]}`;document.getElementById('stagePosition').textContent=`第 ${activeStage+1} 步，共 ${stageIds.length} 步`;window.scrollTo({top:0,behavior:'smooth'})}
    document.getElementById('stageNav').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;showStage(stageIds.indexOf(btn.dataset.target))});
    document.getElementById('previousStageButton').addEventListener('click',()=>showStage(activeStage-1));
    document.getElementById('nextStageButton').addEventListener('click',()=>{if(activeStage===stageIds.length-1)openSummary();else showStage(activeStage+1)});
    document.getElementById('timerButton').addEventListener('click',toggleTimer);document.getElementById('finishButton').addEventListener('click',openSummary);document.getElementById('confirmFinishButton').addEventListener('click',()=>{save();document.getElementById('summaryDialog').close()});
    function toggleJudgement(open){document.body.classList.toggle('judgement-open',open);document.getElementById('openJudgementButton').setAttribute('aria-expanded',open?'true':'false')}
    document.getElementById('openJudgementButton').addEventListener('click',()=>toggleJudgement(true));
    document.getElementById('closeJudgementButton').addEventListener('click',()=>toggleJudgement(false));
    document.getElementById('drawerBackdrop').addEventListener('click',()=>toggleJudgement(false));
    document.addEventListener('keydown',event=>{if(event.key==='Escape')toggleJudgement(false)});
    document.getElementById('copySummaryButton').addEventListener('click',async e=>{await navigator.clipboard.writeText(document.getElementById('summaryOutput').value);e.currentTarget.textContent='已复制';setTimeout(()=>e.currentTarget.textContent='复制纪要',1200)});
    document.getElementById('downloadMarkdownButton').addEventListener('click',()=>{const data=values();download(`${safeName(data)}.md`,summary(data),'text/markdown;charset=utf-8')});document.getElementById('downloadJsonButton').addEventListener('click',()=>{const data=values();download(`${safeName(data)}.json`,JSON.stringify(data,null,2),'application/json;charset=utf-8')});
    document.getElementById('newInterviewButton').addEventListener('click',()=>{if(!confirm('新建访谈会清空当前浏览器中的记录。请先确认已经导出。'))return;localStorage.removeItem(STORAGE_KEY);form.reset();document.querySelectorAll('[data-score]').forEach(el=>el.value='0');document.getElementById('riskScore').value='3';timerSeconds=1800;updateTimer();saveStatus.textContent='已新建访谈';form.elements.interviewDate.value=new Date().toISOString().slice(0,10);updateScores();window.scrollTo({top:0,behavior:'smooth'})});
    const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{restore(JSON.parse(saved));saveStatus.textContent='已恢复本地记录'}catch(_){saveStatus.textContent='本地记录无法读取'}}else form.elements.interviewDate.value=new Date().toISOString().slice(0,10);showStage(0);updateScores();updateTimer();
})();
